.PHONY: install install-local uninstall clean test test-unit test-property test-integration lint format check clean-branches install-skills uninstall-skills bundle-skills stamp-version unstamp-version

BUILD_INFO := agent_fox/_build_info.py

stamp-version:
	@rev=$$(git rev-parse --short HEAD 2>/dev/null) && \
	printf '%s\n' \
		'"""Build-time metadata — autogenerated by make stamp-version."""' \
		'' \
		"GIT_REVISION: str | None = \"$$rev\"" \
		> $(BUILD_INFO) && \
	echo "stamped $(BUILD_INFO) with $$rev"

unstamp-version:
	@git checkout -- $(BUILD_INFO) 2>/dev/null && echo "restored $(BUILD_INFO)" || true

install: stamp-version
	uv tool install --editable .

install-local: stamp-version
	uv pip install --editable ".[vertex]"

uninstall:
	uv tool uninstall agent-fox

clean:
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name '*.pyc' -delete 2>/dev/null || true
	find . -type f -name '*.pyo' -delete 2>/dev/null || true
	rm -rf .pytest_cache/ *.egg-info/ dist/ .ruff_cache/ .mypy_cache/ .hypothesis/

test:
	uv run pytest -q

test-unit:
	uv run pytest tests/unit/ -q

test-property:
	uv run pytest tests/property/ -q

test-integration:
	uv run pytest tests/integration/ -q

lint:
	uv run ruff check agent_fox/ && uv run ruff format --check agent_fox/

format:
	uv run ruff format agent_fox/ tests/

check: lint test

clean-branches:
	@git branch --list 'feature/*' | xargs -r git branch -d

SKILLS_DIR := $(CURDIR)/skills
SKILLS_TEMPLATES_DIR := $(CURDIR)/agent_fox/_templates/skills
CLAUDE_SKILLS_DIR := $(HOME)/.claude/skills

bundle-skills:
	@mkdir -p $(SKILLS_TEMPLATES_DIR)
	@for skill in $(SKILLS_DIR)/*/SKILL.md; do \
		name=$$(basename "$$(dirname "$$skill")"); \
		awk 'BEGIN{fm=0} /^---$$/{fm++; next} fm>=2' "$$skill" > "$(SKILLS_TEMPLATES_DIR)/$$name"; \
		echo "copied: $$skill -> $(SKILLS_TEMPLATES_DIR)/$$name"; \
	done

install-skills:
	@mkdir -p $(CLAUDE_SKILLS_DIR)
	@for skill in $(SKILLS_DIR)/*/; do \
		name=$$(basename "$$skill"); \
		if [ -d "$(CLAUDE_SKILLS_DIR)/$$name" ]; then \
			echo "skip: $$name (already installed)"; \
		else \
			cp -R "$$skill" "$(CLAUDE_SKILLS_DIR)/$$name"; \
			echo "installed: $$name -> $(CLAUDE_SKILLS_DIR)/$$name"; \
		fi; \
	done

uninstall-skills:
	@for skill in $(SKILLS_DIR)/*/; do \
		name=$$(basename "$$skill"); \
		if [ -d "$(CLAUDE_SKILLS_DIR)/$$name" ]; then \
			rm -rf "$(CLAUDE_SKILLS_DIR)/$$name"; \
			echo "removed: $$name"; \
		fi; \
	done